title: "GitHubPagesTemplate"
logo: "/assets/icons/logo.png"
remote_theme: pmarsceill/just-the-docs
color_scheme: "light"
search_enabled: true

callouts_level: quiet
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red