name: Export doc PDF
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: Webpage to PDF
        uses: misaelnieto/web_to_pdf_action@v0.3.1
        with:
          webPageURL: https://www.noenieto.com/resume/
          outputFile: ./export.pdf         
      - uses: actions/checkout@v2
      - uses: actions/upload-artifact@v3
        with:
          name: doc.pdf
          path: ./export.pdf
